Repository innovationacademy-kr/42cabi_admin, pull requests merged in 2022-05, with the labels that each got.

#2 ✅ 코드리뷰 테스트
  backend/app.js
Labels: good first issue

#3 Backend 이슈 closed test
  backend/app.js
Labels: good first issue

#8 :white_check_mark: 깃 테스트용 풀리퀘
  backend/app.js
Labels: CHORE, YUBCHOI

#9 ✨ Add Routes #6
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/Login.tsx
  frontend/src/PageNotFound.tsx
  frontend/src/Pages/Home.tsx
  frontend/src/Pages/Map.tsx
  frontend/src/Pages/Search.tsx
  frontend/src/Pages/Status.tsx
  frontend/src/axiosExample.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
Labels: FEAT, JIWCHOI, JAESJEON

#12 :sparkles: navBar 추가 #10
  frontend/public/assets/cabinet.ico
  frontend/public/assets/cabinet.png
  frontend/public/assets/event.gif
  frontend/public/assets/funnyEvent.gif
  frontend/public/assets/greenMap.png
  frontend/public/assets/logo.png
  frontend/public/assets/logo_purple.png
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/Components/Layout.tsx
  frontend/src/Components/NavBar.tsx
Labels: FEAT, JIWCHOI, JAESJEON

#14 Main page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/Charts/FloorStatusChart.tsx
  frontend/src/Charts/TotalStatusChart.tsx
  frontend/src/Pages/Home.tsx
  package-lock.json
Labels: FEAT, JIWCHOI, JAESJEON

#21 ✨ 검색 기능 api 구현
  backend/app.js
  backend/routes/query.js
Labels: FEAT, YUBCHOI, YOYOO

#22 Yubchoi
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/query.js
  backend/routes/query.js
  backend/util.js
Labels: FIX, YUBCHOI, YOYOO, REFACTOR

#23 ✨ 메인 페이지 차트 완성 #13
  backend/app.js
  backend/routes/query.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/FloorStatusChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Charts/TotalStatusChart.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/Pages/Home.tsx
  frontend/src/type.ts
Labels: FEAT, JIWCHOI

#24 Yubchoi
  backend/app.js
  backend/package.json
  backend/routes/apiRoute.js
  backend/routes/query.js
  backend/server.js
  backend/util.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/CabiButton.tsx
  frontend/src/Components/CabinetDetail.tsx
  frontend/src/Components/Dropdown.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/Components/UserDetail.tsx
  frontend/src/DataTypes.ts
  frontend/src/Pages/NoResult.tsx
  frontend/src/Pages/Search.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/ReduxModules/SearchCabinet.tsx
  frontend/src/ReduxModules/SearchText.tsx
  frontend/src/ReduxModules/SearchType.tsx
  frontend/src/ReduxModules/SearchUser.tsx
  frontend/src/ReduxModules/rootReducer.tsx
  frontend/src/Tables/PrevCabinetTable.tsx
  frontend/src/Tables/PrevUserTable.tsx
  frontend/src/Tables/prevCabinetTableStruct.ts
  frontend/src/Tables/prevUserTableStruct.ts
  frontend/src/Tables/react-table-config.d.ts
  frontend/src/Tables/table.css
  frontend/src/index.tsx
Labels: FIX, YUBCHOI, YOYOO

#27 Yubchoi
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/routes/activationRouter.js
  backend/routes/apiRoute.js
  backend/routes/cabinetRouter.js
  backend/routes/lentRouter.js
  backend/routes/query.js
  backend/routes/returnRouter.js
  backend/routes/searchRouter.js
Labels: YUBCHOI, YOYOO, REFACTOR

#26 Login page #25
  frontend/public/assets/pageNotFound.png
  frontend/src/App.tsx
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Components/Footer.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/Login.tsx
  frontend/src/PageNotFound.tsx
  frontend/src/Pages/Login.tsx
  frontend/src/Pages/Map.tsx
  frontend/src/Pages/PageNotFound.tsx
Labels: CHORE, FEAT

#32 Search tap
  frontend/src/Components/ButtonSet.tsx
  frontend/src/Components/CabinetDetail.tsx
  frontend/src/Components/NoPrevLog.tsx
  frontend/src/Components/Toast.tsx
  frontend/src/Components/ToastStyleComponent.ts
  frontend/src/Components/UserDetail.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ModalStyleComponent.ts
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/Tables/prevCabinetTableStruct.ts
  frontend/src/Tables/prevUserTableStruct.ts
Labels: CHORE, FEAT, JAESJEON

#33 Yubchoi
  backend/routes/activationRouter.js
  backend/routes/query.js
Labels: FEAT, YUBCHOI, YOYOO

#34 Yubchoi
  backend/routes/query.js
Labels: FIX, YUBCHOI, YOYOO

#35 :zap: axios 부분에 try-catch 추가
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Components/NavBar.tsx
Labels: FIX, CHORE, JIWCHOI

#36 :art: Button transform, 오타 수정, 불필요한 조건문 삭제
  frontend/src/Components/CabiButton.tsx
  frontend/src/Components/CabinetDetail.tsx
  frontend/src/Components/ExpiredInfo.tsx
  frontend/src/Components/LentDisabled.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/Components/UserDetail.tsx
  frontend/src/Modals/ModalStyleComponent.ts
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Pages/Status.tsx
  frontend/src/Tables/DisabledTableStruct.ts
  frontend/src/Tables/ExpiredTableStruct.ts
  frontend/src/Tables/PrevCabinetTable.tsx
  frontend/src/Tables/PrevUserTable.tsx
  frontend/src/Tables/prevCabinetTableStruct.ts
  frontend/src/Tables/prevUserTableStruct.ts
  frontend/src/Tables/tableStyleComponent.ts
  frontend/src/axiosExample.tsx
Labels: CHORE

#40 ✨ Login page API 추가 #25
  backend/app.js
  backend/config/config.js
  backend/middleware/authmiddleware.js
  backend/package-lock.json
  backend/package.json
  backend/routes/apiRoute.js
  backend/routes/authRouter.js
  backend/routes/query.js
  backend/util.js
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Pages/Login.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/Pages/Status.tsx
Labels: FEAT, JIWCHOI, JAESJEON

#41 Yoyoo
  backend/middleware/authmiddleware.js
Labels: FEAT, YUBCHOI, YOYOO
