Repository innovationacademy-kr/42cabi_admin, pull requests merged in 2022-06, with the labels that each got.

#45 Yoyoo
  backend/.eslintrc.js
  backend/.prettierrc.json
  backend/app.js
  backend/config/config.js
  backend/middleware/authmiddleware.js
  backend/package-lock.json
  backend/package.json
  backend/routes/activationRouter.js
  backend/routes/apiRoute.js
  backend/routes/authRouter.js
  backend/routes/cabinetRouter.js
  backend/routes/lentRouter.js
  backend/routes/query.js
  backend/routes/returnRouter.js
  backend/routes/searchRouter.js
  backend/util.js
  frontend/src/Pages/Login.tsx
Labels: CHORE, YUBCHOI, YOYOO

#50 Status tap
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/Components/Footer.tsx
  frontend/src/Components/Logout.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Pages/Login.tsx
Labels: FIX, FEAT, JAESJEON

#49 Yubchoi
  .gitignore
  backend/config/database.js
  backend/db/query.js
  backend/routes/activationRouter.js
  backend/routes/cabinetRouter.js
  backend/routes/lentRouter.js
  backend/routes/query.js
  backend/routes/returnRouter.js
  backend/routes/searchRouter.js
  frontend/src/Pages/Login.tsx
Labels: YUBCHOI, YOYOO, REFACTOR

#54 Fe axios
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Networks/APIType.ts
  frontend/src/Pages/Search.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/Pages/Status.tsx
  frontend/src/Tables/DisabledTable.tsx
  frontend/src/Tables/ExpiredTable.tsx
  frontend/src/Tables/disabledTableStruct.ts
  frontend/src/Tables/expiredTableStruct.ts
  frontend/src/Tables/prevCabinetTableStruct.ts
Labels: FIX, CHORE, JIWCHOI, JAESJEON, REFACTOR

#55 Fe_SearchTap refactoring
  frontend/src/Components/DropdownStyleComponent.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/ReduxModules/SearchResponse.tsx
  frontend/src/ReduxModules/SearchType.tsx
  frontend/src/ReduxModules/StatusDisabled.tsx
  frontend/src/ReduxModules/StatusExpired.tsx
  frontend/src/ReduxModules/rootReducer.tsx
  frontend/src/index.tsx
Labels: CHORE, FEAT, JAESJEON, REFACTOR

#58 :art: Add error handling to axiosFormat, Check token in login page #51
  frontend/src/Charts/FloorStateChart.tsx
  frontend/src/Charts/TotalStateChart.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ReturnModal.tsx
  frontend/src/Networks/APIType.ts
  frontend/src/Pages/Login.tsx
  frontend/src/Pages/SearchDashboard.tsx
  frontend/src/Pages/Status.tsx
  frontend/src/index.tsx
Labels: CHORE, JAESJEON

#60 Yoyoo
  backend/app.js
  backend/controller/activationController.js
  backend/controller/authController.js
  backend/controller/cabinetController.js
  backend/controller/lentController.js
  backend/controller/returnController.js
  backend/controller/searchController.js
  backend/db/query.js
  backend/initial-setting/cabinet.sql
  backend/initial-setting/createDisabledLogTable.js
  backend/initial-setting/disabled-log.sql
  backend/initial-setting/user.sql
  backend/jsconfig.json
  backend/package.json
  backend/routes/activationRouter.js
  backend/routes/authRouter.js
  backend/routes/cabinetRouter.js
  backend/routes/lentRouter.js
  backend/routes/returnRouter.js
  backend/routes/searchRouter.js
Labels: YUBCHOI, YOYOO

#67 밴 관련 기능 추가
  backend/config/config.js
  backend/config/database.js
  backend/controller/activationController.js
  backend/controller/authController.js
  backend/db/query.js
  backend/initial-setting/ban.sql
  backend/initial-setting/createTable.js
  backend/package.json
  backend/routes/activationRouter.js
  backend/routes/apiRoute.js
  backend/routes/authRouter.js
  frontend/src/App.tsx
  frontend/src/Components/CabinetDetail.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/Components/UserDetail.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Pages/Login.tsx
  frontend/src/Pages/Task.tsx
  frontend/src/ReduxModules/TaskBanCabinet.tsx
  frontend/src/ReduxModules/TaskBanUser.tsx
  frontend/src/ReduxModules/rootReducer.tsx
  frontend/src/Tables/BanCabinetTable.tsx
  frontend/src/Tables/BanUserTable.tsx
  frontend/src/Tables/banCabinetTableStruct.ts
  frontend/src/Tables/banUserTableStruct.ts
  frontend/src/type.ts
  package-lock.json
Labels: FEAT

#72 Frontend 메뉴 구조 정리
  frontend/public/index.html
  frontend/src/Components/CabinetDetail.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/Components/UserDetail.tsx
  frontend/src/Modals/ActivationModal.tsx
  frontend/src/Modals/ModalStyleComponent.ts
  frontend/src/Pages/Status.tsx
  frontend/src/Pages/Task.tsx
  frontend/src/Tables/BanCabinetTable.tsx
  frontend/src/Tables/BanUserTable.tsx
  frontend/src/Tables/DisabledTable.tsx
  frontend/src/Tables/ExpiredTable.tsx
Labels: CHORE, FEAT
